/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface StEthLeverInterface extends utils.Interface {
  functions: {
    "FLASH_LOAN_RETURN()": FunctionFragment;
    "approveFyToken(bytes6)": FunctionFragment;
    "cauldron()": FunctionFragment;
    "divest(bytes12,bytes6,uint256,uint256,uint256)": FunctionFragment;
    "giver()": FunctionFragment;
    "ilkId()": FunctionFragment;
    "invest(bytes6,uint256,uint256)": FunctionFragment;
    "ladle()": FunctionFragment;
    "onFlashLoan(address,address,uint256,uint256,bytes)": FunctionFragment;
    "stableSwap()": FunctionFragment;
    "steth()": FunctionFragment;
    "weth()": FunctionFragment;
    "wethJoin()": FunctionFragment;
    "wsteth()": FunctionFragment;
    "wstethJoin()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "FLASH_LOAN_RETURN"
      | "approveFyToken"
      | "cauldron"
      | "divest"
      | "giver"
      | "ilkId"
      | "invest"
      | "ladle"
      | "onFlashLoan"
      | "stableSwap"
      | "steth"
      | "weth"
      | "wethJoin"
      | "wsteth"
      | "wstethJoin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "FLASH_LOAN_RETURN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveFyToken",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "cauldron", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "divest",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "giver", values?: undefined): string;
  encodeFunctionData(functionFragment: "ilkId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "ladle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onFlashLoan",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "stableSwap",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "steth", values?: undefined): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(functionFragment: "wethJoin", values?: undefined): string;
  encodeFunctionData(functionFragment: "wsteth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wstethJoin",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FLASH_LOAN_RETURN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveFyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cauldron", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "divest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "giver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ilkId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ladle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onFlashLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stableSwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "steth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wethJoin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wsteth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wstethJoin", data: BytesLike): Result;

  events: {
    "Divested(uint8,bytes12,bytes6,address,uint256,uint256)": EventFragment;
    "Invested(bytes12,bytes6,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Divested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Invested"): EventFragment;
}

export interface DivestedEventObject {
  operation: number;
  vaultId: string;
  seriesId: string;
  investor: string;
  profit: BigNumber;
  debt: BigNumber;
}
export type DivestedEvent = TypedEvent<
  [number, string, string, string, BigNumber, BigNumber],
  DivestedEventObject
>;

export type DivestedEventFilter = TypedEventFilter<DivestedEvent>;

export interface InvestedEventObject {
  vaultId: string;
  seriesId: string;
  investor: string;
  investment: BigNumber;
  debt: BigNumber;
}
export type InvestedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  InvestedEventObject
>;

export type InvestedEventFilter = TypedEventFilter<InvestedEvent>;

export interface StEthLever extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StEthLeverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    FLASH_LOAN_RETURN(overrides?: CallOverrides): Promise<[string]>;

    approveFyToken(
      seriesId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cauldron(overrides?: CallOverrides): Promise<[string]>;

    divest(
      vaultId: PromiseOrValue<BytesLike>,
      seriesId: PromiseOrValue<BytesLike>,
      ink: PromiseOrValue<BigNumberish>,
      art: PromiseOrValue<BigNumberish>,
      minWeth: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    giver(overrides?: CallOverrides): Promise<[string]>;

    ilkId(overrides?: CallOverrides): Promise<[string]>;

    invest(
      seriesId: PromiseOrValue<BytesLike>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      minCollateral: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ladle(overrides?: CallOverrides): Promise<[string]>;

    onFlashLoan(
      initiator: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      fee: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stableSwap(overrides?: CallOverrides): Promise<[string]>;

    steth(overrides?: CallOverrides): Promise<[string]>;

    weth(overrides?: CallOverrides): Promise<[string]>;

    wethJoin(overrides?: CallOverrides): Promise<[string]>;

    wsteth(overrides?: CallOverrides): Promise<[string]>;

    wstethJoin(overrides?: CallOverrides): Promise<[string]>;
  };

  FLASH_LOAN_RETURN(overrides?: CallOverrides): Promise<string>;

  approveFyToken(
    seriesId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cauldron(overrides?: CallOverrides): Promise<string>;

  divest(
    vaultId: PromiseOrValue<BytesLike>,
    seriesId: PromiseOrValue<BytesLike>,
    ink: PromiseOrValue<BigNumberish>,
    art: PromiseOrValue<BigNumberish>,
    minWeth: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  giver(overrides?: CallOverrides): Promise<string>;

  ilkId(overrides?: CallOverrides): Promise<string>;

  invest(
    seriesId: PromiseOrValue<BytesLike>,
    borrowAmount: PromiseOrValue<BigNumberish>,
    minCollateral: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ladle(overrides?: CallOverrides): Promise<string>;

  onFlashLoan(
    initiator: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    borrowAmount: PromiseOrValue<BigNumberish>,
    fee: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stableSwap(overrides?: CallOverrides): Promise<string>;

  steth(overrides?: CallOverrides): Promise<string>;

  weth(overrides?: CallOverrides): Promise<string>;

  wethJoin(overrides?: CallOverrides): Promise<string>;

  wsteth(overrides?: CallOverrides): Promise<string>;

  wstethJoin(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    FLASH_LOAN_RETURN(overrides?: CallOverrides): Promise<string>;

    approveFyToken(
      seriesId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    cauldron(overrides?: CallOverrides): Promise<string>;

    divest(
      vaultId: PromiseOrValue<BytesLike>,
      seriesId: PromiseOrValue<BytesLike>,
      ink: PromiseOrValue<BigNumberish>,
      art: PromiseOrValue<BigNumberish>,
      minWeth: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    giver(overrides?: CallOverrides): Promise<string>;

    ilkId(overrides?: CallOverrides): Promise<string>;

    invest(
      seriesId: PromiseOrValue<BytesLike>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      minCollateral: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    ladle(overrides?: CallOverrides): Promise<string>;

    onFlashLoan(
      initiator: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      fee: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    stableSwap(overrides?: CallOverrides): Promise<string>;

    steth(overrides?: CallOverrides): Promise<string>;

    weth(overrides?: CallOverrides): Promise<string>;

    wethJoin(overrides?: CallOverrides): Promise<string>;

    wsteth(overrides?: CallOverrides): Promise<string>;

    wstethJoin(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Divested(uint8,bytes12,bytes6,address,uint256,uint256)"(
      operation?: PromiseOrValue<BigNumberish> | null,
      vaultId?: PromiseOrValue<BytesLike> | null,
      seriesId?: null,
      investor?: PromiseOrValue<string> | null,
      profit?: null,
      debt?: null
    ): DivestedEventFilter;
    Divested(
      operation?: PromiseOrValue<BigNumberish> | null,
      vaultId?: PromiseOrValue<BytesLike> | null,
      seriesId?: null,
      investor?: PromiseOrValue<string> | null,
      profit?: null,
      debt?: null
    ): DivestedEventFilter;

    "Invested(bytes12,bytes6,address,uint256,uint256)"(
      vaultId?: PromiseOrValue<BytesLike> | null,
      seriesId?: null,
      investor?: PromiseOrValue<string> | null,
      investment?: null,
      debt?: null
    ): InvestedEventFilter;
    Invested(
      vaultId?: PromiseOrValue<BytesLike> | null,
      seriesId?: null,
      investor?: PromiseOrValue<string> | null,
      investment?: null,
      debt?: null
    ): InvestedEventFilter;
  };

  estimateGas: {
    FLASH_LOAN_RETURN(overrides?: CallOverrides): Promise<BigNumber>;

    approveFyToken(
      seriesId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cauldron(overrides?: CallOverrides): Promise<BigNumber>;

    divest(
      vaultId: PromiseOrValue<BytesLike>,
      seriesId: PromiseOrValue<BytesLike>,
      ink: PromiseOrValue<BigNumberish>,
      art: PromiseOrValue<BigNumberish>,
      minWeth: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    giver(overrides?: CallOverrides): Promise<BigNumber>;

    ilkId(overrides?: CallOverrides): Promise<BigNumber>;

    invest(
      seriesId: PromiseOrValue<BytesLike>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      minCollateral: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ladle(overrides?: CallOverrides): Promise<BigNumber>;

    onFlashLoan(
      initiator: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      fee: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stableSwap(overrides?: CallOverrides): Promise<BigNumber>;

    steth(overrides?: CallOverrides): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    wethJoin(overrides?: CallOverrides): Promise<BigNumber>;

    wsteth(overrides?: CallOverrides): Promise<BigNumber>;

    wstethJoin(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    FLASH_LOAN_RETURN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approveFyToken(
      seriesId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cauldron(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    divest(
      vaultId: PromiseOrValue<BytesLike>,
      seriesId: PromiseOrValue<BytesLike>,
      ink: PromiseOrValue<BigNumberish>,
      art: PromiseOrValue<BigNumberish>,
      minWeth: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    giver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ilkId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    invest(
      seriesId: PromiseOrValue<BytesLike>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      minCollateral: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ladle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onFlashLoan(
      initiator: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      borrowAmount: PromiseOrValue<BigNumberish>,
      fee: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stableSwap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    steth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wethJoin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wsteth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wstethJoin(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
